collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: 
      path: ""
    values:
      layout: "default"
      home: false

plugins:
  - jekyll-feed
